### ISSUE TITLE
选项页面缺字

### ISSUE THREAD

**Issue by dragon100a** [lychichem/localized-software-langage-files#3]
![544111111111111111111111111](https://cloud.githubusercontent.com/assets/5362072/8344899/278f9b50-1b1a-11e5-9e35-adeb9c4c5525.png)
看起来是缺字，但我估计可能是长度不够，有啥办法改吗？
版本是3.96

**Comment by lychichem** [comment]
已更新，缩短了一下这里的字数

**Comment by dragon100a** [comment]
那个词是skin，翻译成 皮肤/外观，都好
